services:
  web:
    build: .
    ports:
      - 127.0.0.1:1616:80
    environment:
      - NGINX_PORT=80
  json_exporter:
    image: prometheuscommunity/json-exporter:v0.6.0
    volumes:
      - ./docker/json-exporter.yml:/config.yml:ro
  prometheus:
    image: prom/prometheus:v2.55.0-rc.0
    user: 65534:65534
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/runtime/prometheus:/prometheus
    depends_on:
      - json_exporter
  grafana:
    image: grafana/grafana-enterprise:11.2.1-ubuntu
    depends_on:
      - prometheus
